version: '2'
services:
  postgres-data:
    image: busybox
    volumes:
    - /var/lib/postgresql/data
    container_name: postgres-datastore
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dbsecret
    volumes:
    - ./docker_conf/db_conf/initdb_script:/docker-entrypoint-initdb.d
    expose:
    - 5432
    volumes_from:
    - postgres-data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db